version: "3"
services:
  database:
    image: postgres:11.4-alpine
    container_name: ${APP_NAME}.postgres
    restart: always
    working_dir: ${APP_ROOT_DIR}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../database/data:/var/lib/postgresql/data
      - ../database/dumps:${APP_ROOT_DIR}
    ports:
      - "${COMPOSE_DATABASE_PORT}:${DB_PORT}"
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    build:
      context: nginx
      args:
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
    container_name: ${APP_NAME}.webserver
    restart: always
    working_dir: ${APP_ROOT_DIR}
    environment:
      - APP_HOST=${APP_HOST}
    depends_on:
      - php-fpm
    volumes:
      - ..:${APP_ROOT_DIR}
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/php.general.conf:/etc/nginx/php.general.conf
      - ./nginx/server.general.conf:/etc/nginx/server.general.conf
      - ./nginx/server.headers.general.conf:/etc/nginx/server.headers.general.conf
    ports:
      - "${COMPOSE_WEBSERVER_PORT}:80"
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "netstat -lnp | grep 80"]
      interval: 10s
      timeout: 5s
      retries: 5

  php-fpm:
    build:
      context: php-fpm
      args:
        APP_ROOT_DIR: ${APP_ROOT_DIR}
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
    container_name: ${APP_NAME}.php-fpm
    env_file:
      - ../.env
    restart: always
    image: ${APP_NAME}/php-fpm
    working_dir: ${APP_ROOT_DIR}
    depends_on:
      - database
    volumes:
      - ..:${APP_ROOT_DIR}
      - ./php-fpm/php.ini:/etc/php/7.2/fpm/conf.d/92-overrides.ini
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "ss -lnp | grep 9000"]
      interval: 10s
      timeout: 5s
      retries: 5

  cli:
    build:
      context: php-cli
      args:
        APP_ROOT_DIR: ${APP_ROOT_DIR}
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
        FROM_NAME: ${APP_NAME}/php-fpm
    env_file:
      - ../.env
    container_name: ${APP_NAME}.cli
    working_dir: ${APP_ROOT_DIR}
    user: application
    environment:
      - APP_ROOT_DIR=${APP_ROOT_DIR}
    volumes:
      - ..:${APP_ROOT_DIR}
      - $HOME/.ssh:/home/application/.ssh
      - ./php-fpm/php.ini:/etc/php/7.2/cli/conf.d/92-overrides.ini
    networks:
      - application

networks:
  application:

